//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OYS.Models.veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTOPARKLAR
    {
        public int otoparkID { get; set; }
        public string otoparkAdi { get; set; }
        public string otoparkAdres { get; set; }
        public string otoparkSahibi { get; set; }
        public Nullable<int> otoparkKapasite { get; set; }
        public string otoparkIBAN { get; set; }
        public Nullable<int> ucretlendirme { get; set; }
    }
}
