//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OYS.Models.veritabani
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oysEntities2 : DbContext
    {
        public oysEntities2()
            : base("name=oysEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CIKISLAR> CIKISLAR { get; set; }
        public virtual DbSet<GECMISLER> GECMISLER { get; set; }
        public virtual DbSet<GIRISLER> GIRISLER { get; set; }
        public virtual DbSet<OTOPARKLAR> OTOPARKLAR { get; set; }
        public virtual DbSet<PARKYERLERI> PARKYERLERI { get; set; }
        public virtual DbSet<REZERVASYONLAR> REZERVASYONLAR { get; set; }
        public virtual DbSet<UCRETLER> UCRETLER { get; set; }
        public virtual DbSet<UYELER> UYELER { get; set; }
    }
}
