//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OYS.Models.veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARKYERLERI
    {
        public int parkYeriID { get; set; }
        public int otoparkID { get; set; }
        public string parkYeri { get; set; }
    }
}
