//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OYS.Models.veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class REZERVASYONLAR
    {
        public int rezervasyonID { get; set; }
        public Nullable<int> uyeID { get; set; }
        public Nullable<int> otoparkID { get; set; }
        public string aracPlaka { get; set; }
        public Nullable<System.TimeSpan> rezervasyonSaat { get; set; }
        public string parkYeri { get; set; }
        public Nullable<int> ucret { get; set; }
        public Nullable<System.DateTime> rezarvasyonTarih { get; set; }
    }
}
