//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OYS.Models.veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCRETLER
    {
        public int ucretID { get; set; }
        public Nullable<int> uyeID { get; set; }
        public Nullable<int> girisID { get; set; }
        public Nullable<int> cikisID { get; set; }
        public Nullable<int> otoparkID { get; set; }
        public Nullable<int> ucretlendirme { get; set; }
    }
}
