//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OYS.Models.veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class UYELER
    {
        public int uyeID { get; set; }
        public string uyeAdi { get; set; }
        public string uyeSoyadi { get; set; }
        public string uyeEmail { get; set; }
        public string uyeTelefon { get; set; }
        public string uyeKullaniciAdi { get; set; }
        public string uyeSifre { get; set; }
    }
}
